version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: cd delivery && gradle clean build
  tests:
    docker:
      - image: circleci/openjdk:11.0.2
    steps:
      - checkout
      - run: gradle test
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - tests:
          requires:
            - build